name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  go:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: ['1.18']
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/setup-python@v2
 
    - name: build binary
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o tubed *.go