name: Publish

on:
  release:
    types: [published]

jobs:

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.Version=${{ github.event.release.tag_name }}'" -o tubed *.go
          tar -cvzf tubed_${{ github.event.release.tag_name }}_linux_amd64.tar.gz tubed
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: tubed_${{ github.event.release.tag_name }}_linux_amd64.tar.gz